title: Riddhi Dave Portfolio
description: Hi! My Name is Riddhi. I am recent graduate from George Brown collge. This github page will demonstrate my skills 
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
